# https://prettier.io/docs/en/configuration.html

# General rules
tabWidth: 2
useTabs: true
semi: true
singleQuote: true
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: true
# Overrides rules
overrides:
  # SCSS
  - files:
      - './src/styles/**/*.scss'
    options:
      singleQuote: false
